# node_a.toml - Linear topology: Mining node
p2p_listen = "0.0.0.0:9001"
rpc_listen = "0.0.0.0:8545"
db_path = "/data"
snapshots_path = "/data/snapshots"
snapshot_interval = 100
snapshot_keep = 3
seeds = []

[db]
write_buffer_mb = 256
block_cache_mb = 512
compression = "lz4"

[mempool]
max_bytes = 52428800  # 50 MB
max_orphans = 100
min_relay_fee_sat_vb = 1
orphan_ttl_secs = 600
