# node_c.toml - Linear topology: Sync from node_b
p2p_listen = "0.0.0.0:9003"
rpc_listen = "0.0.0.0:8547"
db_path = "/data"
snapshots_path = "/data/snapshots"
snapshot_interval = 100
snapshot_keep = 3
# Fixed IP addresses for Docker Compose network
seeds = ["172.28.0.11:9002"]  # node_b

[db]
write_buffer_mb = 256
block_cache_mb = 512
compression = "lz4"

[mempool]
max_bytes = 52428800
max_orphans = 100
min_relay_fee_sat_vb = 1
orphan_ttl_secs = 600
