[advisories]
# Note: We migrated from pqcrypto-dilithium to pqcrypto-mldsa (NIST ML-DSA standard)
# RUSTSEC-2024-0436: paste crate is unmaintained but has no security vulnerabilities
# It's a transitive dependency from pqcrypto-mldsa and cannot be avoided until
# pqcrypto-mldsa updates or we find an alternative PQC library
ignore = [
    "RUSTSEC-2024-0436", # paste - unmaintained (transitive dep from pqcrypto-mldsa)
]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Unlicense",
]
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
