[package]
name = "pow"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
consensus = { path = "../consensus", version = "0.1.0" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tx = { path = "../tx", version = "0.1.0" }
