[package]
name = "pow"
version = "0.1.0"
edition = "2024"

[dependencies]
consensus = { path = "../consensus" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
tx = { path = "../tx" }
