version: "3.9"

services:
  node_a:
    image: pqpriv:dev
    user: "0:0"  # Run as root to avoid permission issues with volumes
    command: ["run", "--config", "/home/pqpriv/node_a.toml"]
    ports:
      - "8644:8644"
      - "8645:8645"
    volumes:
      - node_a_data:/home/pqpriv/.pqpriv/node
      - node_a_snapshots:/home/pqpriv/.pqpriv/snapshots
      - ./node_a.toml:/home/pqpriv/node_a.toml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8645/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
  node_b:
    image: pqpriv:dev
    user: "0:0"  # Run as root to avoid permission issues with volumes
    command: ["run", "--config", "/home/pqpriv/node_b.toml"]
    depends_on:
      node_a:
        condition: service_healthy
    ports:
      - "8744:8744"
      - "8745:8745"
    volumes:
      - node_b_data:/home/pqpriv/.pqpriv/node
      - node_b_snapshots:/home/pqpriv/.pqpriv/snapshots
      - ./node_b.toml:/home/pqpriv/node_b.toml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8745/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  node_a_data:
  node_a_snapshots:
  node_b_data:
  node_b_snapshots:
