p2p_listen = "0.0.0.0:8744"
rpc_listen = "0.0.0.0:8745"
# Note: seeds require IP addresses, not hostnames
# Comment out seeds for Docker testing - nodes will bootstrap without pre-configured peers
# seeds = ["172.18.0.2:8644"]  # Example if you know node_a's IP
db_path = "/home/pqpriv/.pqpriv/node"
snapshots_path = "/home/pqpriv/.pqpriv/snapshots"
snapshot_interval = 120
snapshot_keep = 2
sync_orphan_limit = 8192
