[package]
name = "node"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
blake3 = "1.5"
codec = { path = "../codec" }
consensus = { path = "../consensus" }
crypto = { path = "../crypto" }
pow = { path = "../pow" }
tx = { path = "../tx" }
utxo = { path = "../utxo" }
p2p = { path = "../p2p" }
hex = "0.4"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
anyhow = "1.0"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread", "net", "signal", "time", "sync"] }
axum = { version = "0.7", features = ["macros", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
