# cargo-audit configuration
# https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example

[advisories]
# Ignore RUSTSEC-2024-0436: paste crate is unmaintained
# This is a transitive dependency from pqcrypto-mldsa (NIST ML-DSA standard library)
# and cannot be avoided until pqcrypto-mldsa updates or we find an alternative PQC library.
# The advisory is only about maintenance status, not a security vulnerability.
ignore = [
    "RUSTSEC-2024-0436",  # paste - unmaintained (transitive from pqcrypto-mldsa)
]
