[package]
name = "consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.5"
num-bigint = "0.4"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tx = { path = "../tx" }
codec = { path = "../codec" }
crypto = { path = "../crypto" }
