# star.yml - Star topology: Hub ↔ Leaf1, Leaf2, Leaf3
#
# Test scenario:
#   - Hub node mines blocks
#   - Three leaf nodes sync from hub
#   - Alternating mining can be tested by enabling --mine on leaves
#   - Track orphan rate and reorg behavior
#
# Usage:
#   docker compose -f docker/e2e/star.yml up --build --abort-on-container-exit
#
# Verification:
#   - All nodes converge to same tip
#   - Low orphan rate (< 5%)
#   - Minimal reorgs

services:
  hub:
    image: pqpriv:dev
    container_name: pq_star_hub
    environment:
      - E2E_FIXED_GENESIS=1
    command:
      - "run"
      - "--config=/config/star_hub.toml"
    volumes:
      - ./data/star/hub:/data
      - ./config:/config:ro
    networks:
      star_net:
        ipv4_address: 172.29.0.10
    ports:
      - "9010:9010"
      - "8550:8550"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8550/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  leaf1:
    image: pqpriv:dev
    container_name: pq_star_leaf1
    environment:
      - E2E_FIXED_GENESIS=1
    command:
      - "run"
      - "--config=/config/star_leaf1.toml"
    volumes:
      - ./data/star/leaf1:/data
      - ./config:/config:ro
    networks:
      - star_net
    ports:
      - "9011:9011"
      - "8551:8551"
    depends_on:
      hub:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8551/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  leaf2:
    image: pqpriv:dev
    container_name: pq_star_leaf2
    environment:
      - E2E_FIXED_GENESIS=1
    command:
      - "run"
      - "--config=/config/star_leaf2.toml"
    volumes:
      - ./data/star/leaf2:/data
      - ./config:/config:ro
    networks:
      - star_net
    ports:
      - "9012:9012"
      - "8552:8552"
    depends_on:
      hub:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8552/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  leaf3:
    image: pqpriv:dev
    container_name: pq_star_leaf3
    environment:
      - E2E_FIXED_GENESIS=1
    command:
      - "run"
      - "--config=/config/star_leaf3.toml"
    volumes:
      - ./data/star/leaf3:/data
      - ./config:/config:ro
    networks:
      - star_net
    ports:
      - "9013:9013"
      - "8553:8553"
    depends_on:
      hub:
        condition: service_healthy

networks:
  star_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
