[package]
name = "crypto"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
blake3 = "1.5"
hex = "0.4"
rand = "0.9"
rand_chacha = "0.3"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
sha3 = "0.10"
thiserror = "1.0"
ed25519-dalek = "2.1"
