name: Benchmark Tracking

on:
  push:
    branches: [main, feat/privacy/stark-phase]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bench-
            ${{ runner.os }}-cargo-

      - name: Run STARK benchmarks
        run: cargo bench --package crypto-stark --bench stark_perf -- --output-format bencher | tee stark_bench.txt

      - name: Run TX v2 benchmarks
        run: cargo bench --package node --bench tx_v2_perf -- --output-format bencher | tee tx_v2_bench.txt

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: stark_bench.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: false
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            stark_bench.txt
            tx_v2_bench.txt
            target/criterion/

      - name: Comment PR with benchmark results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const starkBench = fs.readFileSync('stark_bench.txt', 'utf8');
            const txBench = fs.readFileSync('tx_v2_bench.txt', 'utf8');
            
            const body = `## Benchmark Results

            ### STARK Performance
            \`\`\`
            ${starkBench}
            \`\`\`

            ### TX v2 Performance
            \`\`\`
            ${txBench}
            \`\`\`
            
            _Benchmark data is also available in the [Criterion report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})._
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
