name: CI

on:
  push:
    branches: ["main", "work", "feature/**"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: lint + test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.90.0
          components: clippy, rustfmt

      - name: Cache cargo directories
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Tests
        run: cargo test --workspace --all-targets --locked

      - name: Install cargo-deny
        if: matrix.os == 'ubuntu-latest'
        run: cargo install cargo-deny --locked

      - name: Cargo deny
        if: matrix.os == 'ubuntu-latest'
        run: cargo deny check

      - name: Install cargo-audit
        if: matrix.os == 'ubuntu-latest'
        run: cargo install cargo-audit --locked

      - name: Cargo audit
        if: matrix.os == 'ubuntu-latest'
        run: cargo audit --deny warnings
