[package]
name = "tx"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_with = { version = "3.4", features = ["macros"] }
thiserror = "1.0"
codec = { path = "../codec" }
crypto = { path = "../crypto" }
